docs(configuration): fix closing punctuation for matches in examples (#2886)
Summary:
Changed two instances of: `` matches = "sub/**` `` to fix unterminated string errors in config examples.

```
error: Failed to parse: `pyproject.toml`
  Caused by: TOML parse error at line 33, column 19
   |
33 | matches = "sub/**`
   |                   ^
invalid basic string, expected `"`
```

Pull Request resolved: https://github.com/facebook/pyrefly/pull/2886

Reviewed By: rchen152, ndmitchell

Differential Revision: D98568589

Pulled By: yangdanny97

fbshipit-source-id: 3259b1663300958c529b3d702815b688b5d9d3d6