Feat/import autocomplete (#3084)
Summary:
earlier exported symbols were appearing only when we had importedName for the module.
for eg.
`from math import sq`

here , `sq` is the `importedName`

since it has chars for importedName the completion suggestion will show symbols for it, but in case when

`from math import`

there is no importedName the completion suggestion won't work since  `from_stmt_import_from_name` fn in `pyrefly/lib/state/lsp.rs` require importedName.

so I added `importedNameEmpty` to match the condition for `from math import |` and trigger completion when there's no name. after that i made sure that `ThisModule` entries appear first, so i marked them `Local` in completion source. and did `Reexport` for `OtherModule` entries.

up until now i was able to trigger completion and symbols are appearing as expected but pyrefly/test are failing due to difference in ordering in the suggestions, so i would like to discuss should we change the ordering inside tests or is there other way out?

one test error eg.

```
2 | from foo import func
  |                 ^^^^
  |

thread 'test::lsp::completion::from_import_deprecated' (22054) panicked at pyrefly/lib/test/lsp/completion.rs:769:5:
assertion failed: `(left == right)`

Diff < left / right > :
 # main.py
 2 | from foo import func
                ^
 Completion Results:

 2 | from foo import func
                         ^
 Completion Results:
<- (Variable) deprecated
 - (Function) func_ok
>- (Variable) deprecated
```

Fixes https://github.com/facebook/pyrefly/issues/2999

Pull Request resolved: https://github.com/facebook/pyrefly/pull/3084

Test Plan:
- Manually verified in VS Code using a local Pyrefly build from this branch.
  - Opened a Python file with `from math import |` and triggered completion.
  - Confirmed symbol-like `math` exports are shown (for example `sqrt`, `sin`, `cos`) and unrelated helper suggestions are shown at bottom.
  - Also verified `from math import s|` still returns expected symbol completions.

Reviewed By: stroxler

Differential Revision: D102338009

Pulled By: kinto0

fbshipit-source-id: c3362cceebfa861e769a63006f534ca7e7b2cd63