Enable num-bigint "serde" feature
Summary:
This feature is required by buck2's `pagable` crate.

Found while working on {D102213623}.

```lang=log,counterexample
error[E0599]: the method `serialize` exists for reference `&BigInt`, but its trait bounds were not satisfied
  --> fbcode/buck2/pagable/src/impls.rs:48:17
   |
48 |         Ok(self.serialize(serializer.serde())?)
   |                 ^^^^^^^^^
   |
  ::: third-party/rust/vendor/num-bigint-0.4.6/src/bigint.rs:57:1
   |
57 | pub struct BigInt {
   | ----------------- doesn't satisfy `BigInt: inner::_::_serde::Serialize`
   |
   = note: the following trait bounds were not satisfied:
           `BigInt: inner::_::_serde::Serialize`
           which is required by `&BigInt: inner::_::_serde::Serialize`
   = help: items from traits can only be used if the trait is implemented and in scope
note: `ArcEraseDyn` defines an item `serialize`, perhaps you need to implement it
  --> fbcode/buck2/pagable/src/arc_erase.rs:43:1
   |
43 | pub trait ArcEraseDyn: std::any::Any + Send + Sync + 'static {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0277]: the trait bound `BigInt: serde::Deserialize<'de>` is not satisfied
  --> fbcode/buck2/pagable/src/impls.rs:57:12
   |
57 |         Ok(Deserialize::deserialize(deserializer.serde())?)
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Deserialize<'_>` is not implemented for `BigInt`
   |
   = note: for local types consider adding `#[derive(serde::Deserialize)]` to your `BigInt` type
   = note: for types from other crates check whether the crate offers a `serde` feature flag
   = help: the following other types implement trait `Deserialize<'de>`:
             &'a Path
             &'a RelativePath
             &'a [u8]
             &'a serde_json::value::RawValue
             &'a str
             ()
             (T,)
             (T0, T1)
           and 200 others
```

Reviewed By: diliop

Differential Revision: D102232267

fbshipit-source-id: b48ca431b28f5bd01dbaf1cd0b905425c22f0f7e